### ISSUE TITLE
Directly play on the server

### ISSUE THREAD

**Issue by imraansarwar** [noamtcohen/AudioStreamer#13]
Hi, thanks for the solution, simple and nice.
I need to play the sound in real time instead of saving it. Any suggestions, how can I achieve it?

Regards

**Comment by gabssnake** [comment]
You could use the [speaker](https://www.npmjs.com/package/speaker) module.

```js
const Speaker = require('speaker')

const speaker = new Speaker({
  channels: 1,
  bitDepth: 16, // samples
  sampleRate: 44100 // Hz
})

stream.on("data", buffer => speaker.write(buffer))
```

Best,
