### ISSUE TITLE
Error while saving Mp3

### ISSUE THREAD

**Issue by Keyne** [noamtcohen/AudioStreamer#14]
There's a problem on lame encoder when encoding to Mp3 returning segmentation fault. I've just downloaded the project files and changed config.json to Mp3. Is there any configuration in lame that should be done prior to executing the code?

**Comment by noamtcohen** [comment]
Works on my side...
but, sampleRate was hardcoded: https://github.com/noamtcohen/AudioStreamer/blob/fa87cb7bb16b78eea8c9005b5f404a70c6538082/server/server.js#L63
so i've changes this and committed, please pull and try again

**Comment by Keyne** [comment]
Well, this is strange, I'm facing this problem in all tests I've done. This is why I'm suspecting there's something wrong with lame. 

With the updated code, I can only get the mp3 file if I change to 2 channels instead of 1, on the lame config. But the audio is kind of fast-forwarded instead of normal timing. If I set to 1 channel, I got segmentation fault. Is there anything I'm missing?

**Comment by noamtcohen** [comment]
Try opening an issue with https://github.com/TooTallNate/node-lame

**Comment by Keyne** [comment]
What's your OS?

 I'm reproducing this in a virtual machina Ubuntu 16 from osboxes.org.
I've made a fresh installation with apt-get install lame before testing... Please let me know if you can confirm the same

**Comment by noamtcohen** [comment]
I'm running OSX 10.12.6

**Comment by bobaikato** [comment]
After the start, what port is this running on?

**Comment by noamtcohen** [comment]
https://localhost:9191

**Comment by bobaikato** [comment]
Thanks

**Comment by Keyne** [comment]
I'm closing this issue as I'm not facing this problem anymore. I've done several modifications and can't tell exactly what was wrong, but it seems like there's no problem with lame.
