### ISSUE TITLE
Saving chunks of audio instead of a single file

### ISSUE THREAD

**Issue by arliber** [noamtcohen/AudioStreamer#15]
Hello,

I want to process the live stream coming from the browser and for that, I'll need to save small chunks, say 2 seconds each of the audio.
The end result might look something like 1.wav, 2.wav, 3.wav etc. where every file is 2 seconds long.

I tried different approaches but was unable to make it work properly.

I would appreciate any help :)

Thanks!

**Comment by noamtcohen** [comment]
instead of stream.pipe: https://github.com/noamtcohen/AudioStreamer/blob/master/server/server.js#L56
use ```stream.on('data',function(chunk){...})```
check the size of the chunk, when you reached 2 seconds close the wav file stream and create a new one.

**Comment by arliber** [comment]
Great, thank you very much!
