### ISSUE TITLE
How to use the resampler?

### ISSUE THREAD

**Issue by yakitimor** [noamtcohen/AudioStreamer#7]
Hi Noam

I noticed you have added a re-sampler code,  I tried loading it on the client page together with the site.js, etc...
In the server.js, still when I change the sample rate to anything that is 44100, the sound is distorted, because its working only on the playback.
Its a great solution and with the option to lower the bit rate (lower the sample), it can be economic and more reliable. Right now its using more than 700kbps.

Thanks,
Yaki

**Comment by noamtcohen** [comment]
Hi and Thanks,
I've pushed a commit that uses the reSampler please pull the repo and tell me if this fixes your issue.
N

**Comment by yakitimor** [comment]
Thanks a lot for the quick response, I am trying to make it work with the
new code, for now, its still , probably on my end, I am still checking the
differences and let you know.

YT

**Comment by noamtcohen** [comment]
What does the audio sound like after it is received by the server?
Could you post a file?

**Comment by yakitimor** [comment]
There wasn't any audio stream, the waves canvas didn't move as if there is
no connection Usually if there is a sampling issue, its either distorted,
faster or slower.
I took the new server.js and site.js, configured the same address's and
ports as before, loaded the re-sampler on the html and still nothing.

**Comment by noamtcohen** [comment]
Are you sure your mic is working properly?
What browser are you using, did you check that the right input device is selected in the browser?
What do you see in the browser console and node console?
I'm not sure what is the problem, I tested the code on OS X+chrome with a Logitech webcam mic.
Speed issues are because of the wav header not having the correct sample rate. but this can't happen with the reSampler since the sample rate is defined in one place.

**Comment by yakitimor** [comment]
Using Chrome on Windows machine.
With the old code its working well,just by reverting back to the 2 old
files, also with the new one its selecting the right, it prompts you the
right to use the mic (from the dell laptop).
The symptom is that the "Start" button doesn't continue to really streaming
as if the server is not responding.
Is the re-sampler really changing the sampling rate on the browser/OS level
or its taking the original 41KHz sampling and lose the sampling rate (as it
does with the 32 bits to 16bits )?

**Comment by noamtcohen** [comment]
What do you see on the browser console? I'll look into this more later on.

**Comment by yakitimor** [comment]
First thanks a lot!
Its working now.
My audio is passing through a cloud server, then to a Raspberry Pi, this is
where it got broken.
I used the old code on the Pi server.js file, set it manually to the
desired sample rate and let the site.js do the re-sampling with setting the
reSampling var.

Thanks again,
YT

**Comment by noamtcohen** [comment]
enjoy
