### ISSUE TITLE
Chrome crashes after few minutes with re-sampler

### ISSUE THREAD

**Issue by yakitimor** [noamtcohen/AudioStreamer#8]
The re-smapler code works after the last change and I could use it with sample rate of 8000 (128kbps), also the delay is better ; however, the Chrome browser crashes after a few minutes.
The chrome doesn't leave anything that I could catch in debug, it just moves suddenly to the "Ah snap. something went wrong..."
I tried increasing the buffer with no help, but what I did notice is that if the page I am using has additional traffic, like a player streaming it crashes much faster and when reverting to without the re-sampler, it doesn't happen.
Any idea how to debug it?

**Comment by noamtcohen** [comment]
Could you try putting the resampling code in a webworker?

**Comment by yakitimor** [comment]
I am less familiar with this tool and meantime, I went backward as the
Chrome allows the getUserMedia() to work only from an https site. The
Firefox dont crashes, but simply stops the streamer after 20-30 secs.
Is there a way I can contact you privately?

Yaki

**Comment by noamtcohen** [comment]
@yakitimor do you want to give me your email?

**Comment by yakitimor** [comment]
Added to my profile.

Thanks,
Yaki

**Comment by noamtcohen** [comment]
I've updated the re-sampler code
