### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by marke123** [noamtcohen/AudioStreamer#9]
Hi, I downloaded a copy of this project and installed it on my localhost to test. When I run the server.js with nodejs a browser tab opens automatically to https://localhost:9191 and nothing loads from the server. I see a message on the browser screen saying "Cannot GET /", and there's no output in the console from the server. I tried this in Firefox and Chrome, same error in both. 

Any idea why?

I also noticed that in site.js for the client you have this: 
socket = new WebSocket('ws://localhost:9000/demo');
but the server listens on 9191, so I'm not sure why it points to port 9000 over an insecure connection (ws://).

**Comment by noamtcohen** [comment]
Are you sure you pulled `master` latest? 
This is what I see on site.js: `client = new BinaryClient('wss://'+location.host);`

https://github.com/noamtcohen/AudioStreamer/blob/master/public/js/site.js#L23

**Comment by marke123** [comment]
Apparently I somehow got the wrong copy. Apologies for that. 

So I reinstalled today. When I ran server.js there was a "file not found" error for ssl/server.key. That is located one directory up from the server dir so I copied the ssl dir into the server dir and then the server started Ok. But, still the same thing with "Cannot GET /" in the browser.

**Comment by noamtcohen** [comment]
If you had to move the ssl dir it probably means you are in the wrong working directory. 

These are the steps you need to take:

``` bash
git clone https://github.com/noamtcohen/AudioStreamer.git AudioStreamer
cd AudioStreamer/
npm install
npm start
```

Are you sure that this is what you are doing?

**Comment by noamtcohen** [comment]
@marke123 did this work for you?

**Comment by lonewolfaka9** [comment]
how to play recording on different browser

**Comment by noamtcohen** [comment]
This is not in the scope of the project. 
You have an audio file, you can encode it to mp3 and server it to an audio tag.
To encode to mp3 see this pull request: https://github.com/noamtcohen/AudioStreamer/pull/10

**Comment by lonewolfaka9** [comment]
The name of project says AudioStreamer so i got confused . it just record audio stream and save to server :( 

```
On Monday, May 16, 2016 4:27 PM, noamtcohen <notifications@github.com> wrote:
```

 This is not in the scope of the project. 
You have an audio file, you can encode it to mp3 and server it to an audio tag.
To encode to mp3 see this pull request: #10—

**Comment by noamtcohen** [comment]
it's a one way project. lol ;-)

**Comment by marcolino** [comment]
I'm using your "one-way" project with great satisfaction :-)
I'd like to add mp3 encoding, server-side. I was thinking to someway merge a project like https://github.com/TooTallNate/node-lame, to start an encoding on the server when a wav fileis available. Any thoughts about this idea? Any suggestion, or counter-suggestions ;-) ?

... Sorry! I didn't read PR #10... :-( It's about exactly this same issue...  Do you plan accepting it? Or should I better fork to have mp3 encoding, too?

**Comment by noamtcohen** [comment]
Hi Marcolino, If you could please confirm that PR #10  is working correctly, I will accept it.
Thanks for the feedback, N.

**Comment by marcolino** [comment]
It works perfectly form me. But be warned that the patch _comments out_ the
wav file save, and enables the mp3 file save (no option handling). For me
it's fine...

Il 08/nov/2016 17:07, "noamtcohen" notifications@github.com ha scritto:

**Comment by noamtcohen** [comment]
OK, I'll accept it. Thanks for you r help.
I think I'll add a configuration option for this some how, maybe a `config.json` file
